<?php

/*
 * Integrity checks for stubs/react/manifest.php (published by `laravilt:install --stack=react`).
 */

function reactStubsPath(string $path = ''): string
{
    return dirname(__DIR__, 2).'/stubs/react'.($path !== '' ? '/'.$path : '');
}

function reactStubManifest(): array
{
    return require reactStubsPath('manifest.php');
}

/**
 * All stub files (relative to stubs/react), excluding the manifest itself.
 *
 * @return list<string>
 */
function reactStubFiles(): array
{
    $root = reactStubsPath();
    $files = [];

    $iterator = new RecursiveIteratorIterator(new RecursiveDirectoryIterator($root, FilesystemIterator::SKIP_DOTS));

    foreach ($iterator as $file) {
        $relative = str_replace('\\', '/', substr($file->getPathname(), strlen($root) + 1));

        if ($relative !== 'manifest.php') {
            $files[] = $relative;
        }
    }

    sort($files);

    return $files;
}

/**
 * Map of every published stub file => its app-relative target path.
 *
 * @return array<string, string>
 */
function reactPublishedFiles(): array
{
    $published = [];

    foreach (reactStubManifest()['publish'] as $source => $target) {
        if (is_dir(reactStubsPath($source))) {
            foreach (reactStubFiles() as $file) {
                if (str_starts_with($file, $source.'/')) {
                    $published[$file] = $target.substr($file, strlen($source));
                }
            }

            continue;
        }

        $published[$source] = $target;
    }

    return $published;
}

it('points every publish entry at an existing stub', function () {
    $manifest = reactStubManifest();

    expect($manifest)->toHaveKeys(['publish', 'delete']);

    foreach ($manifest['publish'] as $source => $target) {
        expect(file_exists(reactStubsPath($source)))->toBeTrue("Missing stub for manifest entry [{$source}]");
        expect($target)->toBeString()->not->toBeEmpty();
    }
});

it('publishes every React stub file', function () {
    $unpublished = array_values(array_diff(reactStubFiles(), array_keys(reactPublishedFiles())));

    expect($unpublished)->toBe([]);
});

it('only imports @/ modules that are published, generated by Wayfinder, or shipped by the starter kit', function () {
    $targets = array_values(reactPublishedFiles());
    $deleted = reactStubManifest()['delete'];

    // Files the Laravel React starter kit ships that the stubs rely on but do not publish
    $starterKit = [
        'resources/js/hooks/use-clipboard.ts',
        'resources/js/hooks/use-flash-toast.ts',
        'resources/js/hooks/use-mobile.tsx',
        'resources/js/hooks/use-mobile-navigation.ts',
    ];

    // Generated by @laravel/vite-plugin-wayfinder
    $generatedPrefixes = ['resources/js/routes', 'resources/js/actions', 'resources/js/wayfinder'];

    $unresolved = [];

    foreach (reactPublishedFiles() as $source => $target) {
        if (! preg_match('/\.(tsx?|stub)$/', $source)) {
            continue;
        }

        preg_match_all('/(?:from\s+|import\s*\(\s*)[\'"]@\/([^\'"]+)[\'"]/', file_get_contents(reactStubsPath($source)), $matches);

        foreach ($matches[1] as $import) {
            $base = 'resources/js/'.$import;

            foreach ($deleted as $path) {
                if ($base === $path || str_starts_with($base, $path.'/') || str_starts_with($path, $base.'.')) {
                    $unresolved[] = "{$source} imports deleted @/{$import}";

                    continue 2;
                }
            }

            foreach ($generatedPrefixes as $prefix) {
                if ($base === $prefix || str_starts_with($base, $prefix.'/')) {
                    continue 2;
                }
            }

            $candidates = [$base.'.ts', $base.'.tsx', $base.'.d.ts', $base.'/index.ts', $base.'/index.tsx'];

            if (array_intersect($candidates, [...$targets, ...$starterKit]) === []) {
                $unresolved[] = "{$source} imports @/{$import}";
            }
        }
    }

    expect($unresolved)->toBe([]);
});
